# -*- coding: utf-8 -*-
"""Essential Python for DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VaCmf4Vckj2LPr0NrRtHNqTR-N4uyQg

**OOP**
"""

class Dog:
    def __init__(self, name, species, age):
        self.name = name
        self.species = species
        self.age = age

    def bark(self):
        print(f"{self.name} is barking 'hong hong'!")

    def hbd(self):
        self.age += 1 #เขีนยแบบเต็มจะเป็น self.age = self.age + 1

dog1 = Dog("Milo", "Chihuahua", 2)
dog2 = Dog("David", "Husky", 3)

print(f"{dog1.name} is {dog1.species}")

print(f"{dog2.name} is {dog2.species}")

dog1.bark()

dog2.bark()

print(dog1.age)
dog1.hbd()
print(dog1.age)

##homework
class ATM:
    def __init__(self, username, bank, amount, password):
        self.username = username
        self.bank = bank
        self.amount = amount
        self.password = password


    def __str__(self):
        return f"{self.username} uses {self.bank} and has {self.amount} THB in an account."

    def check_balance(self):
        print(f"Balance: {self.amount} THB")

    def deposit(self, saving):
        self.amount += saving
        print(f"Deposit {saving} THB successfully")

    def withdraw(self, withdraw):
        self.amount -= withdraw
        print(f"Withdraw {withdraw} THB successfully")

    def transfer(self, target_account, amount):
        if self.amount >= amount:
            self.amount -= amount
            target_account.amount += amount

            print(f"You transfer {amount} to {target_account.username} successfully.")
        else:
            print(f"Error: Insufficient balance")

    def pin_code(self, password):
        if self.password == password:
            print(f"Welcome to our service.")
        else:
            print(f"wrong password")

    def top_up(self, amount, phone_number):
        if self.amount >= amount:
            self.amount -= amount
            print(f"You topped up {self.amount} THB to phone number {phone_number}.")
            print(f"Remaining balance: {self.amount} THB")
        else:
            print(f"Failed to top up because Your current balance is {self.amount} THB.")

toy = ATM("Kasidis Toy", "scb", 100, "123456")
friend = ATM("Olive Kint", "Kbank", 300, "000000")

print(f"{toy.username} opens a new account at {toy.bank}.")

toy.check_balance()

toy.deposit(200)

toy.check_balance()

print(toy)

toy.withdraw(100)

toy.check_balance()

toy.transfer(friend, 100)

toy.pin_code(123456)

friend.pin_code("000001")

toy.check_balance()

toy.top_up(100, "0814329051")

toy.check_balance()

"""**Super class**"""

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

##extension
class Employee(Person):
    def __init__(self, name, age, company):
        super().__init__(name, age)
        self.company = company

    def greeting(self):
        print("Hello world")

toy = Person("toy", 37)

toy.name, toy.age

person1 = Person("toy", 37)

person2 = Employee("lisa", 28, "google")

person2.greeting()



"""**Try Exxept Block**"""

try:
    result = 1/0
except:
    print("This is an error message!")

!pwd

!cat hotel.csv

##read file
import csv

try:
    file = open("hotel.csv", "r")
    data = csv.reader(file)
    for row in data:
        print(row)
    file.close()
except:
    print("File not found, please check file name again.")
finally:
    print("read file successfully")

"""Context Maanger"""

read_data = []

with open("hotel.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        read_data.append(row)

read_data[0]

read_data[1: ]

##for loop to calculate price per night
prices = []

for row in read_data[1: ]:
    prices.append(int(row[4]))

print(f"average price per night: {sum(prices)/ len(prices)}")

##modern python
import pandas as pd

df = pd.read_csv("hotel.csv")

df.head()

df.price_per_night.mean()

df["price_per_night"].mean()

#write file + context manager
head = ["id", "name", "city"]
body = [
    [1, "CU", "Bangkok"],
    [2, "LSE", "London"],
    [3, "Reading", "Reading"]
]

with open("school.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(head)
    writer.writerows(body)

!ls

!cat school.csv

##modern pandas
import pandas as pd

df = pd.read_csv("school.csv")

df.head()

#export csv
df.to_csv("school2.csv")

!ls

!cat school2.csv

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

import pandas as pd
df_penguin = pd.read_csv(url)

df_penguin.head()

df_penguin.tail()

##select column
df_penguin[["species", "island", "body_mass_g"]].head(10)

#filter rows
df_penguin[["species", "island", "body_mass_g"]] \
.query("species == 'Adelie' and island == 'Dream'") \
.head(10)

#filter without query()
df_penguin[df_penguin['body_mass_g'] >= 4500][["species", "sex", "body_mass_g"]]

import requests

##api endpoint
url = "https://swapi.info/api/people/1"

response = requests.get(url)

response.json()["name"]

response.json()["height"]

response.json()["mass"]

##for loop
import requests
import time

character =[]

for i in range(5):
    url = f"https://swapi.info/api/people/{i+1}"
    response = requests.get(url)
    response_json = response.json()
    data = (response_json["name"],
            response_json["height"],
            response_json["mass"])
    character.append(data)
    print(f"Success: {i+1}")
    time.sleep(1)

print(character)

import pandas as pd
starwars = pd.DataFrame(character, columns = ["name", "height", "mass"])

starwars

import requests
import time

characters = []


for i in range(4):
    url = f"https://api.attackontitanapi.com/characters/{i+1}"
    response = requests.get(url)
    response_json = response.json()
    data = (response_json["name"],
            response_json["age"],
            response_json["gender"])
    characters.append(data)
    print(f"Success: {i+1}")
    time.sleep(1)

print(characters)

